# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 876af051d94858726dd0d98cc91317837da9e17a047493dc3072d7ec5de9c7cddf9104b85ca601ea1de1aab8143242b0fbe321e677aa0a57ef698af493c3799c

test:
  secret_key_base: 0c6af5fdc82dc60650c32f9b158a3f8aa80dcc43f29b6ba32cc3986a1db2191138aad414e10081769a26ed355866cb9b75a9dc13462746aae7c0da95449a574b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
